<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-P3GFGE6" failures="1" tests="5" name="Test1" time="101.5" errors="0" timestamp="2024-04-17T15:51:27 IST">
  <testcase classname="TestNG.DemoTest" name="createProduct" time="17.917"/>
  <testcase classname="TestNG.DemoTest" name="createUserAcc" time="21.296"/>
  <testcase classname="TestNG.sampleTest" name="Admin_billing" time="10.642"/>
  <testcase classname="TestNG.sampleTest" name="UpdateInventory" time="8.822"/>
  <testcase classname="TestNG.sampleTest" name="User_billing" time="11.512">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG.sampleTest.User_billing(sampleTest.java:124)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- User_billing -->
  <testcase classname="com_Tyss_Fiducia_GenericUtility.BaseClass" name="@BeforeSuite connectToDB" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite connectToDB -->
</testsuite> <!-- Test1 -->
